pull_request_rules:
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - "#approved-reviews-by >= 1"
      - author = renovate
    actions:
      merge:
        method: merge
