pull_request_rules:
  - name: Automatically merge Dependabot PRs
    conditions:
      - author = dependabot[bot]
    actions:
      queue:
  - name: Automatically merge Renovate PRs
    conditions:
      - author = renovate[bot]
    actions:
      queue:
  - name: Automatically merge Gitlocalize PRs
    conditions:
      - author = gitlocalize-app[bot]
    actions:
      queue:
queue_rules:
  - allow_queue_branch_edit: true
    update_method: merge
    name: default
    merge_method: fast-forward
merge_protections_settings:
  reporting_method: check-runs
