pull_request_rules:
  - name: Automatically merge Renovate PRs
    conditions:
      - author = renovate[bot]
    actions:
      merge:
queue_rules:
  - queue_branch_merge_method: fast-forward
    allow_queue_branch_edit: true
    update_method: merge
    name: default
