version = 1

[[analyzers]]
name = "dart-analyze"
type = "community"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]  
name = "black"  

[[transformers]]  
name = "autopep8"

[[transformers]]  
name = "isort"

[[transformers]]  
name = "prettier"

[[transformers]]  
name = "yapf"

[[transformers]]  
name = "ruff"
