site_name: Chatacter
repo_url: https://github.com/alphaspheredotai/chatacter
repo_name: Chatacter
site_author: MH0386
nav:
    - Home: index.md
    - Doc: docs.md
    - Policy: policy.md
theme:
    name: material
    palette:
        primary: black
        accent: light blue
        scheme: slate
    font:
        text: JetBrains Mono
        code: JetBrains Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.expand
        - navigation.path
        - navigation.indexes
        - toc.follow
        - search.suggest
        - search.share
        - navigation.footer
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.highlight
        - content.tabs.link
        - content.code.annotate
        - content.code.copy
markdown_extensions:
    - attr_list
plugins:
    - search
    # - optimize
    - social
    - git-revision-date-localized:
          enable_creation_date: true
    - git-committers:
          repository: alphaspheredotai/chatacter
          branch: main
extra:
    social:
        - icon: octicons/mark-github-16
          link: https://github.com/alphaspheredotai/chatacter
        - icon: octicons/mail-16
          link: mailto:alpha-AI@googlegroups.com
copyright: Copyright &copy; 2024 <a href="https://alphaspheredotai.github.io"  target="_blank" rel="noopener">AlphaSphere.AI</a>
