site_name: Chatacter
repo_url: https://github.com/alphaspheredotai/chatacter
repo_name: Chatacter
site_author: MH0386
copyright: Copyright &copy; 2025 <a href="https://alphaspheredotai.is-a.dev"  target="_blank" rel="noopener">AlphaSphere.AI</a>
nav:
    - Home: index.md
    - Installation: install.md
    - Documentation: docs.md
    - Policy: policy.md
theme:
    language: en
    icon:
        logo: simple/chatbot
    name: material
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
    font:
        text: JetBrains Mono
        code: JetBrains Mono
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.tracking
        - navigation.expand
        - navigation.path
        - navigation.indexes
        - toc.follow
        - search.suggest
        - search.share
        - navigation.footer
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.highlight
        - content.tabs.link
        - content.code.annotate
        - content.code.copy
markdown_extensions:
    - attr_list
plugins:
    - search
    # - optimize
    - social
    - git-revision-date-localized:
          enable_creation_date: true
    - git-committers:
          repository: alphaspheredotai/chatacter
          branch: main
extra:
    alternate:
        - name: English
          link: /chatacter/
          lang: en
        - name: Arabic
          link: /chatacter/ar/
          lang: ar
    analytics:
        feedback:
            title: Was this page helpful?
            ratings:
                - icon: material/emoticon-happy-outline
                  name: This page was helpful
                  data: 1
                  note: >-
                      Thanks for your feedback!
                - icon: material/emoticon-sad-outline
                  name: This page could be improved
                  data: 0
                  note: https://github.com/AlphaSphereDotAI/chatacter/issues/new/?title=[Feedback]+{title}+-+{url}
