site_name: Chatacter
repo_url: https://github.com/MH0386/graduation_project
site_author: MH0386
nav:
    - Home: index.md
    - Documentation: docs.md
    - Policy: policy.md
theme:
    name: material
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: grey
          accent: light blue
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: black
          accent: light blue
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
    font:
        text: JetBrains Mono
        code: Roboto Mono
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.expand
        - navigation.path
        - navigation.indexes
        - toc.follow
        - search.suggest
        - search.share
        - navigation.footer
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.highlight
        - content.tabs.link
        - content.code.annotate
        - content.code.copy
markdown_extensions:
    - attr_list
plugins:
    - search
extra:
    social:
        - icon: octicons/mark-github-16
          link: https://github.com/MH0386/graduation_project
        - icon: octicons/mail-16
          link: mailto:alpha-AI@googlegroups.com
copyright: Copyright &copy; 2024 <a href="https://alphaspheredotai.github.io"  target="_blank" rel="noopener">AlphaSphere.AI</a>
