site_name: Chatacter
repo_url: https://github.com/alphaspheredotai/chatacter
repo_name: Chatacter
site_author: MH0386
nav:
    - Home: index.md
    - Installation: install.md
    - Documentation: docs.md
    - Policy: policy.md
theme:
    language: en
    name: material
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/weather-night
            name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/weather-sunny
            name: Switch to dark mode
    font:
        text: JetBrains Mono
        code: JetBrains Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.expand
        - navigation.path
        - navigation.indexes
        - toc.follow
        - search.suggest
        - search.share
        - navigation.footer
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.highlight
        - content.tabs.link
        - content.code.annotate
        - content.code.copy
markdown_extensions:
    - attr_list
plugins:
    - search
    # - optimize
    - social
    - git-revision-date-localized:
          enable_creation_date: true
    - git-committers:
          repository: alphaspheredotai/chatacter
          branch: main
copyright: Copyright &copy; 2025 <a href="https://alphaspheredotai.github.io"  target="_blank" rel="noopener">AlphaSphere.AI</a>
