project:
    type: website

website:
    title: "Chatacter"
    search: true
    page-navigation: true
    back-to-top-navigation: true
    twitter-card: true
    page-footer: "Copyright 2021, Norah Jones"
    navbar:
        background: dark
        left:
            - index.qmd
            - about.qmd
            - docs.qmd
            - policy.qmd
        tools:
            - icon: twitter
              href: https://twitter.com
            - icon: github
              href: https://github.com
format:
    html:
        theme: darkly
        css: styles.css
        toc: true
