name: dart
on:
    push:
        branches: main
    pull_request:
jobs:
    Frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
                  restore-keys: ${{ runner.os }}-pub-
            - name: Set up Flutter
              uses: subosito/flutter-action@v2.13.0
              with:
                  channel: "stable"
            - run: flutter pub get
            - run: flutter pub upgrade
            - run: flutter pub outdated
            - run: dart format .
            - run: flutter analyze
