name: Django

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5.0.0
            - name: Install Dependencies
              run: python -m pip install --upgrade pip && cd Backend && pip install -r requirements.txt
            - name: Run Tests
              run: cd Backend && python manage.py test
