name: 'Gitbook Action Build'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v3
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@latest
      with:                                
        token: ${{ secrets.PERSONAL_TOKEN }}
